version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/tickets-db:/data/db
    logging:
      driver: none

  api:
    build:
      context: api
    restart: always
    depends_on:
      - mongo
    volumes:
      - api-build:/opt/application/api-build
      - /data/tickets-storage:/data/storage
    env_file: api/production.env
    healthcheck:
      test: curl -s -w '%{http_code}' http://localhost:3000/api/describe
      timeout: 5s
      interval: 10s

  nginx:
    build:
      context: nginx
    restart: always
    depends_on:
      - api
    ports:
      - 8280:80
    volumes:
      - api-build:/opt/application/api
      - web-build:/var/www/html

volumes:
  api-build:
  web-build:
  api-storage:
